name: xlocker_3
description: "X-Camp Project untuk XLocker."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.8
  thingsboard_pe_client: ^1.2.1
  http: ^0.13.4
  provider: ^6.0.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^6.0.5
  open_settings: ^2.0.2
  url_launcher: ^6.3.0
  loading_animation_widget:
  internet_connection_checker: ^1.0.0+1
  get: ^4.6.6
  logging: ^1.0.2
  esp_smartconfig: ^2.0.4
  flutter_bloc: ^8.1.6
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/x_camp_logo.png
    - assets/profile_image.png
    - assets/x_camp_splashscreen.png
    - assets/teks_smartlocker.png
    - assets/bg_atas.png
    - assets/bg_bawah.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf


